### ISSUE TITLE
Color scheme Base16

### ISSUE THREAD

**Issue by rafaeluriarte** [jarolrod/vim-python-ide#10]
First, thank you for sharing your vim configuration. I have a question regarding the color schemes. I installed the base16 but when I enter vim, the colors look very different from your screenshot (and very difficult to read). When I type color scheme it shows base16-default-dark... Please, find attached the screenshot.
![vim](https://user-images.githubusercontent.com/19567189/56432825-25984800-62cf-11e9-8e94-cab4f367d06c.png)

Any idea on what could be the problem?
Thank you!

**Comment by caco13** [comment]
Same for me.

**Comment by rafaeluriarte** [comment]
I solved the problem some weeks ago but I can't remember how. Here is a part of my .zshrc, give it a try (the folder where I installed  https://github.com/chriskempson/base16-shell.git ):

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

**Comment by jarolrod** [comment]
I have removed base16 as a dependency, please reinstall the config
