### ISSUE TITLE
Error at start after installation (second start)

### ISSUE THREAD

**Issue by conloos** [jarolrod/vim-python-ide#13]
I i get the following error:

```bash
"test2.py" 41L, 6379C
Fehler beim Ausführen von "function pymode#init":
Zeile    2:
E121: Undefinierte Variable: import
Zeile    3:
E121: Undefinierte Variable: sys
Zeile    4:
E121: Undefinierte Variable: sys
Fehler beim Ausführen von "/home/BODOMOS/frank/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim":
Zeile    3:
E121: Undefinierte Variable: from
Fehler beim Ausführen von "function pymode#breakpoint#init":
Zeile    9:
E15: ungültiger Ausdruck: << EOF
Zeile   11:
E492: Kein Editorbefehl: from importlib.util import find_spec
Zeile   13:
E110: Fehlendes ')'
Zeile   19:
E170: Fehlendes :endfor
Tagbar: Exuberant ctags not found!
Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Fehler beim Ausführen von "function tagbar#autoopen[9]..<SNR>160_IsValidFile":
Zeile   29:
E121: Undefinierte Variable: s:known_types
E116: Ungültige Argumente für die Funktion has_key(s:known_types, a:ftype)
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
```

**Comment by DarioHett** [comment]
sudo apt-get install ctags

**Comment by Pyansakon** [comment]
I get this too. A I'm try to "install ctags" like this.
---------------------------------------------------------------------------------------------
parin@parin-desktop:~$ sudo apt-get install ctags
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ctags is a virtual package provided by:
  universal-ctags 0+git20200824-1
  exuberant-ctags 1:5.9~svn20110310-13
You should explicitly select one to install.

E: Package 'ctags' has no installation candidate
---------------------------------------------------------------------------------------------------
help me please 
ubuntu 20.10
