### ISSUE TITLE
ImportError: No module named 'git' when I start Vim

### ISSUE THREAD

**Issue by sagnibak** [jarolrod/vim-python-ide#5]
On Ubuntu 16.04 running on Windows Subsystem for Linux, whenever I am running `vim`, it is giving the following error:
```
Error detected while processing /home/sagnick/.vimrc:
line  403:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named 'git'
Press ENTER or type command to continue
```
If I press enter, it opens vim like normal. Please note that I am quite new to Vim, so I am not sure if what is appearing is normal or not. I have attached two screenshots as well.

![image](https://user-images.githubusercontent.com/23586947/38840860-79bfa884-4196-11e8-8ce1-855621023206.png)

![image](https://user-images.githubusercontent.com/23586947/38840983-f8a63dd4-4196-11e8-8b08-f61a5081c6ee.png)

In the second image, there seems to be a Python-related error (right at the bottom), but I have no idea how to even look at the complete error. I would really appreciate some help!

**Comment by Braincoke** [comment]
Hi,
As stated in the error message, the problem comes from this part of your .vimrc file : 
```python
 python3 << EOF
 import vim
 import git
 def is_git_repo():
       try:
           _ = git.Repo('.', search_parent_directories=True).git_dir
           return "1"
       except:
           return "0"
 vim.command("let g:pymode_rope = " + is_git_repo())
 EOF    
```

As you can see this is some python code trying to import the module `git` and you don't seem to have it on your computer. You can install it by running `pip3 install gitpython` (you might need to prepend `sudo -H` to the command line for it to work).

**Comment by macsiwase** [comment]
I'm still getting the same error even after installing gitpython

**Comment by caco13** [comment]
> Hi,
> As stated in the error message, the problem comes from this part of your .vimrc file :
> 
> ```python
>  python3 << EOF
>  import vim
>  import git
>  def is_git_repo():
>        try:
>            _ = git.Repo('.', search_parent_directories=True).git_dir
>            return "1"
>        except:
>            return "0"
>  vim.command("let g:pymode_rope = " + is_git_repo())
>  EOF    
> ```
> 
> As you can see this is some python code trying to import the module `git` and you don't seem to have it on your computer. You can install it by running `pip3 install gitpython` (you might need to prepend `sudo -H` to the command line for it to work).

For me `sudo pip3 install gitpython` solved. Thanks @Braincoke.

**Comment by viktorvillalobos** [comment]
The same error, i think the error comes from "import vim" line, what package is that?
